### ISSUE TITLE
"math domain error"

### ISSUE THREAD

**Issue by doublex** [bond005/vad#2]
Testcase: [err.wav.gz](https://github.com/bond005/vad/files/5317607/err.wav.gz)

Command line:
````
python3 detect_voice.py -s /tmp/err.wav -d /dev/stdout -c config/config_for_adapt_vad.json
````

stderr:
````
Traceback (most recent call last):
  File "detect_voice.py", line 33, in <module>
    bounds_of_speech = list(detect_spoken_frames(sound, fs, method_params))
  File "/tmp/vad/vad.py", line 201, in detect_spoken_frames
    energy_th = params['Energy_PrimThresh'] * math.log(min_energy)
ValueError: math domain error
````

**Comment by acidcoma** [comment]
Hello! I am also facing the same issue.
